### ISSUE TITLE
[all] Sharing of code using functions

### ISSUE THREAD

**Issue by tpetricek** [wrattler/wrattler#130]
- You have to put all reusable functions into a separate file?
- Or should we let you do this inside Wrattler?

**Comment by tpetricek** [comment]
For loading *.py files, it looks like Jupyter has a special command to do this using %load:
https://stackoverflow.com/questions/21034373/how-to-load-edit-run-save-text-files-py-into-an-ipython-notebook-cell

I suppose that we don’t want exactly the same thing, but if we can get something like this to work, that would be a good start!

This is a bit tricky in our context though, because when you say `%load some.py`, the file `some.py` exists in JupyterLab environment (we can presumably load it in the browser), but the Python service does not know about it at all – so I guess doing this will require work both in the JupyterLab Wrattler client and in the service. I guess that:

-	When an R or Python cell contains %load <filename>, the client will have to use some regular expression to find out that this is there, get the file name and fetch the file from JupyterLab using some API that JupyterLab provides.
-	It can then get the contents of the file and attach it somehow as an additional field to the JSON sent to the /eval end-point of the service. 
-	The service will then need to load the functions from the file first (somehow) before actually running the code.

**Comment by nbarlowATI** [comment]
Another approach (easier to implement but perhaps not as flexible) would just be to mount the same local (e.g. wrattler/public ) directory on both the client and jupyterlab containers.  This way a file saved in jupyterlab would be visible to the client, which could then send its contents to the server.

From a user perspective, what we're looking at implementing is different from the %load magic in jupyter notebooks - these literally paste the file contents into a cell when executed so that the functions etc. defined there are available in the next cell.   We would be doing the %load and also the code that uses the loaded definitions in the same cell.

**Comment by tpetricek** [comment]
I think there should be a way to get the contents of a file through the JupyterLab JavaScript API, but if we cannot figure out how to do that, we can try other tricks.

Here are some thoughts on how this could be done:

 - The [Extension Developer Guide](https://jupyterlab.readthedocs.io/en/stable/developer/extension_dev.html) has an example of "state database" where plugin has a dependency on some other feature of Jupyter - in this case, the `IStateDB` interface.

 - It also has a section on "Core tokens" which - I suspect - is a list of services we can ask for (`IStateDB` is one of those).

 - Another token is `@jupyterlab/docmanager:IDocumentManager`, which looks like something that we could use for looking at the files ([docs](https://jupyterlab.github.io/jupyterlab/docmanager/interfaces/idocumentmanager.html)). There is also `@jupyterlab/filebrowser:IFileBrowserFactory` which might be useful too ([docs](https://jupyterlab.github.io/jupyterlab/filebrowser/modules/ifilebrowserfactory.html))

 - I'm not sure if this lets us do exactly what we need, i.e. get contents of a file with given name - but I guess this is where we can look. (And if we cannot figure it out, ask someone from Jupyter team for advice!)
