### ISSUE TITLE
[client] Show "add below" when there are no cells

### ISSUE THREAD

**Issue by tpetricek** [wrattler/wrattler#180]
If you open empty file, you do not see anything, because we only show "add below" or "add above" when there already is some cell

**Comment by myyong** [comment]
Added "wellcome" cell to empty notebook here d40dbd6

**Comment by tpetricek** [comment]
This is a nice trick :-), but I think this does not completely solve the problem - you can still remove this Welcome cell and be left with an empty notebook without any way of adding anything.

I think it would be nice if we extracted the code that [creates the controls bar](https://github.com/wrattler/wrattler/blob/develop/client/src/main.ts#L156) into a function and generated this one more time above all the individual cells - that way, we'll have one panel with "add" buttons at the top and then, again, below every cell.
