### ISSUE TITLE
[services] "received string but not json format"

### ISSUE THREAD

**Issue by tpetricek** [wrattler/wrattler#182]
Python (and R?) services should not try to store invalid data in the data store. If a variable is not a data frame, it should be ignored.

**Comment by nbarlowATI** [comment]
This should now be fixed for the python service in commit 8c585e23dab6b6b0c0c4c7bcdca365b656909757 in the topic-modelling-example branch.  

For R, the service won't try to store anything that's not a dataframe, but R also tries much harder to coerce things into being dataframes (e.g. strings), so we do end up with some things on the datastore that don't make much sense as dataframes.  But as long as no-one tries to use them in other cells I guess this isn't a huge issue.
