### ISSUE TITLE
[services] Importing matplotlib creates an empty figure

### ISSUE THREAD

**Issue by tpetricek** [wrattler/wrattler#186]
If you run

```
import matplotlib.pyplot as plt
```
you get an empty `Figure1`

**Comment by nbarlowATI** [comment]
This should now be fixed by commit 318b04164f8452d60a249e92ecbc0fc2aa1d81cc  which checks if matplotlib.pyplot.get_fignums() has more than zero entries.
Also calls close() after writing the png file, and removes png file from TMPDIR after sending to the datastore.
