### ISSUE TITLE
Implement previews for exported data frames

### ISSUE THREAD

**Issue by tpetricek** [wrattler/wrattler#39]
When I write some code in Python or JS that exports some data frame, I should see tabs where I can click to see a preview of data in each data frame.

To do this, we will need to modify the `render` function in `javascriptEditor` and `pythonEditor` (this will probably be shared code, so maybe we can do it first in Python and then put it into a separate file and use it from JS too).

The `render` function gets `cell` of type `BlockState` as an argument. From this, it can find `exports` of the cell. It should then look at the `exports` to see if they have `value` and if so (and if the value is an array of records), then it should render a table with a preview.

**Comment by myyong** [comment]
@tpetricek  Do we want to evaluate before previewing?

**Comment by myyong** [comment]
I have done a pull request here: https://github.com/wrattler/wrattler/commit/a968d58d5ff3019a587a4b3e265938375d00d8d2 for this feature.

**Comment by tpetricek** [comment]
Duplicate of #47
