### ISSUE TITLE
Cannot edit Python code

### ISSUE THREAD

**Issue by tpetricek** [wrattler/wrattler#40]
It seems `Shift+Enter` in Python cells does not work. To reproduce:

 - `Evaluate` Python code block
 - Edit the Python code
 - Hit Shift+Enter to update the code

At this point, I'd expect the `Evaluate` button to appear so that I can run updated Python code, but this does not happen. 

As a workaround:

 - Go to some JavaScript cell
 - Hit Shift Enter there 
 - Evaluate button for the Python cell appears
 - When I click it, the correct new Python result appears

**Comment by myyong** [comment]
Fix here: https://github.com/wrattler/wrattler/commit/38f8cf67b88eafc84893b5fc1d5ca633e711445c
