### ISSUE TITLE
Dataframe interface for Node

### ISSUE THREAD

**Issue by myyong** [wrattler/wrattler#43]
Current Graph.Node interface:
```
interface Node {
  /** Language of the plugin that created and owns this node */
  language: string;

  /** Returns all nodes that this node depends on in any way */
  antecedents: Node[]
  
  /**  The evaluated value associated with this node */
  value: any
}
```

Proposed:
value: Langs.DataFrame

The current interface for Langs.DataFrame is 

```
interface DataFrame extends Value {
  url : string
  data : any
}
```

**Comment by tpetricek** [comment]
Not all values will be data frames - for example, TheGamma will have other kinds. But all values will be `Value`, so the `Node` interface should have `value: Value`.
