### ISSUE TITLE
Generate tables with data frame preview

### ISSUE THREAD

**Issue by tpetricek** [wrattler/wrattler#47]

**Comment by myyong** [comment]
Table for python plugin here: commit 71b67d07c124c1e73fb539bd4193a38a0612c1fb

**Comment by tpetricek** [comment]
To implement the tabs, we need to add the current tab index to the editor state (so that we know which is selected) and we need to add an event that is triggered when the user clicks on tab. For JS, this would be something like:

```
interface JavaScriptSwitchTabEvent {
  kind: "switchtab"
  index: number
}
type JavascriptEvent = JavaScriptSwitchTabEvent

type JavascriptState = {
  id: number
  block: JavascriptBlockKind
  selectedTab: number
}
```

This is following the same pattern we're using in `main.ts` with `NotebookEvent` and `NotebookState`.

We then need to update the `render` and `update` functions in `javascriptEditor` so that:

 * `update` will do a `switch` on the event and when `kind` equals `switchtab`, it should return a state where the `selectedTab` is set to the index specified in the event

 * `render` will render a list of buttons (or links) with click handlers. In the click handlers, it should trigger the `JavaScriptSwitchTabEvent` using something like `context.trigger({kind:"switch", index:i})`. Below the buttons, it will then render the preview for the selected variable (it needs to find which one is selected using the index we keep in the state)

**Comment by tpetricek** [comment]
Let's close this when we have it working for JavaScript too
