### ISSUE TITLE
Run Giovanni's R code inside Wrattler 

### ISSUE THREAD

**Issue by tpetricek** [wrattler/wrattler#56]
Should be doable after #53, #54, #55.

**Comment by tpetricek** [comment]
Sub-issues:

 - Make input data accessible via file system (mount Docker directory?)
 - Install necessary R packages (just add them to Docker image)
 - There are some dataviz calls - ignore those for now, use JS later?

**Comment by myyong** [comment]
This is an anonymised, public sample of cleanEHR data (source: https://github.com/ropensci/cleanEHR/blob/master/data/sample_ccd.RData)

I've uploaded it as a blob, and can access it using R with:
```r 
library(httr)
r <- GET("https://cleanehr.blob.core.windows.net/cleanhr/sample_ccd.RData")
```

Sending `r <- GET("https://cleanehr.blob.core.windows.net/cleanhr/sample_ccd.RData")` to the RServer returns:

```json
{"status":"error","status_code":500,"error":"Error : No method asJSON S3 class: request\n"}
```

**Comment by nbarlowATI** [comment]
Hmm... so r is the http response object, which seems to be xml, and its recognised as an "export" of the code fragment, so the R service then tries to write it back to the datastore, but is unable to convert it into JSON..
I'm not sure how we should decide which exports we really want to write to the dataframe.. as a first (possibly temporary) step, i'm implementing a tryCatch in writeFrame that sees whether something is able to be converted into JSON, and won't try to put on the datastore if it isn't..

**Comment by tpetricek** [comment]
I guess we should skip over things that cannot be reasonably converted into data frames - if we call `as.data.frame(r)`, then it fails, so that's a good indicator we should skip that.

Regarding the RData file from the web, the following way of loading it works for me:

```
install.packages("cleanEHR")
file <- paste(tempdir(), "/ccd.rdata", sep="")
download.file("https://github.com/ropensci/cleanEHR/raw/master/data/sample_ccd.RData", file)
load(file)
```

I guess we might run into similar troubles, because `file` is a string, not a data frame, so we'll need the skipping logic anyway.
