### ISSUE TITLE
Error reported from R service /exports

### ISSUE THREAD

**Issue by tpetricek** [wrattler/wrattler#73]
I'm getting an error in a notebook containing even the most basic R code:

    three <- data.frame(name=c("Jim"), age=c(51))

The `/exports` endpoint of the R service gives me:

```
{"status":"error","status_code":500,"error":"Error in parse(text = codeToParse) : 
<text>:1:31: unexpected input\n1: wrattlerParsedCode <- quote({ \r\n                                  ^\n"}
```

My Docker was behaving funny, so perhaps I just have an old version of the service running, but I recall seeing this error before. Alas, the R service does not print much in console out, so I cannot see what's happening there.

It looks as if the R service was not actually pasting the code properly inside `quote`, because it looks like the body is missing there - but I'm not sure what this means.

**Comment by nbarlowATI** [comment]
Hmm... I also think I have seen this error before, but I can't currently reproduce it in the branch nb_wip_df_json that has the latest changes in..
I will see if I can add some verbose console out options to the R service though..
