### ISSUE TITLE
python code parsing identifies exports that may be out of scope

### ISSUE THREAD

**Issue by nbarlowATI** [wrattler/wrattler#80]
The python AST parsing finds all assignments in the code and returns them as "exports", but some of them may be out of scope at the end of the function wrattler_f() which is constructed.  An example code fragment:
```
def hello():
        x = pd.DataFrame({"xx":[1,2,3]})
        return x
newx = hello()
```
here, "exports" will contain both "x" and "newx",  but "x" is undefined outside the scope of hello.

**Comment by tpetricek** [comment]
I think that we cannot get this 100% right and that's expected - if this happens, we might have some extra links in the dependency graph, so things will re-evaluate more frequently than they'd need, but otherwise, it will not cause any concrete issues.

So, I would not be too worried about this.
