### ISSUE TITLE
Payload too large for datastore PUT method

### ISSUE THREAD

**Issue by myyong** [wrattler/wrattler#86]
Working with the cleanEHR dataset gives us ~1800 patients, as opposed to the 30 we were using with public sample. However, we are running into payload too large issues with the datastore.

Stackoverflow suggests that with Node, there is a way to define max size of the payload, but not sure how to do this in f#. @tpetricek can you help?

Error: 
```
wrattler_data_store_1_27a651b62c9b | [16:19:28 INF] Error parsing HTTP request with Payload too large
wrattler_data_store_1_27a651b62c9b | [16:19:28 INF] Error parsing HTTP request with Payload too large
```
so the dataframe is not written, but a URL is still associated with that dataframe. Later, trying to access the dataframe throws
```
wrattler_data_store_1_27a651b62c9b | [16:20:40 INF] Reading blob: b0dc20c1325cbeefeafcaf9e8d3657af/dts
wrattler_data_store_1_27a651b62c9b | [16:20:40 INF] Read blob: b0dc20c1325cbeefeafcaf9e8d3657af/dts (length = -1)
```

**Comment by tpetricek** [comment]
A simple repro is to create JavaScript cell with 

```
var one = [{'name':'Joe with much longer name than previously with much longer name than previously', 'age':-1}]
for(var i = 0; i < 100000; i++)
    one.push({'name':'Joe with much longer name than previously with much longer name than previously', 'age':i})
```
