### ISSUE TITLE
Multiple imports

### ISSUE THREAD

**Issue by myyong** [wrattler/wrattler#91]
We have duplicates of imports and exports coming out of the http://localhost:7101/exports endpoint.

![screenshot 2018-12-05 at 10 10 47](https://user-images.githubusercontent.com/5417696/49506518-2d9ea080-f876-11e8-885b-2f5366e37ab5.png)

**Comment by tpetricek** [comment]
Ha! That looks like a possible cause for some of the performance issues.

I think this should probably be handled on the service side - it should not return duplicates.

**Comment by nbarlowATI** [comment]
This should hopefully be fixed by commit 3c8aa67441b0b7e1cc97e37ca7c6bab7b87d1780 for the python service, and 30a9ae721b9a08ce4b9ae6fde502c13b4761c8e8 for the R service (imports were already OK for R, but exports were previously duplicatable).  

Both commits are on the speed-check branch.
